# Generated by Django 4.0.1 on 2022-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='1', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
